# docker-compose.yml

version: '3.8'

services:
  medchat:
    build:
      context: .
    ports:
      - "80:80"

  medchatapi:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
